
Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-credential-initializer-bhqg9[0m
{"level":"info","ts":1600779569.5122476,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1600779569.5128002,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-working-dir-initializer-2kmj5[0m
{"level":"info","ts":1600779571.1042368,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1600779571.107524,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-place-tools[0m

Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-git-source-seldonio-mlserver-pr-4-pr-build-bbtpg-wqxcs[0m
{"level":"info","ts":1600779577.465992,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/0.8.0-ns-support: no such file or directory"}
{"level":"info","ts":1600779578.8560083,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/SeldonIO/MLServer.git @ master in path /workspace/source"}

Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-setup-builder-home[0m

Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:f1c603722767bba5d629adc58a07f01ca25a677a,4:f7403a930a575c08d372dcf3a433b4b8a36ab024
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow f7403a930a575c08d372dcf3a433b4b8a36ab024: f1c603722767bba5d629adc58a07f01ca25a677a:
DEBUG: ran git fetch --unshallow origin f7403a930a575c08d372dcf3a433b4b8a36ab024: f1c603722767bba5d629adc58a07f01ca25a677a: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard f1c603722767bba5d629adc58a07f01ca25a677a
DEBUG: ran git reset --hard f1c603722767bba5d629adc58a07f01ca25a677a in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge f7403a930a575c08d372dcf3a433b4b8a36ab024
DEBUG: ran git merge f7403a930a575c08d372dcf3a433b4b8a36ab024 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e f1c603722767bba5d629adc58a07f01ca25a677a..HEAD
Merged SHA f7403a930a575c08d372dcf3a433b4b8a36ab024 with commit message 'Use core-builder' into base branch master
Merged SHA 00f5c7717693f077808ca6b23fdfa3ccdd5d49a8 with commit message 'Add owners file' into base branch master
Merged SHA f8f3bf2cd6c1b1d291bcd6185884d1011831e24e with commit message 'Add version to Makefile and Jenkins-x config' into base branch master

Showing logs for build [32mseldonio-mlserver-pr-4-pr-build-bbtpg-2[0m stage [32mtest-python[0m and container [32mstep-test-python[0m
pip install -r requirements-dev.txt
Collecting grpcio-tools==1.29.0
  Downloading grpcio_tools-1.29.0-cp36-cp36m-manylinux2010_x86_64.whl (2.4 MB)
Collecting datamodel-code-generator==0.5.1
  Downloading datamodel_code_generator-0.5.1-py3-none-any.whl (63 kB)
Collecting pytest==5.4.3
  Downloading pytest-5.4.3-py3-none-any.whl (248 kB)
Collecting pytest-asyncio==0.14.0
  Downloading pytest_asyncio-0.14.0-py3-none-any.whl (11 kB)
Collecting tox==3.18.0
  Downloading tox-3.18.0-py2.py3-none-any.whl (82 kB)
Collecting numpy==1.18.5
  Downloading numpy-1.18.5-cp36-cp36m-manylinux1_x86_64.whl (20.1 MB)
Collecting flake8==3.8.3
  Downloading flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting flake8-black==0.2.0
  Downloading flake8-black-0.2.0.tar.gz (8.6 kB)
Collecting mypy==0.782
  Downloading mypy-0.782-cp36-cp36m-manylinux1_x86_64.whl (20.8 MB)
Collecting mypy-protobuf==1.23
  Downloading mypy_protobuf-1.23-py3-none-any.whl (7.4 kB)
Collecting black==19.10b0
  Downloading black-19.10b0-py36-none-any.whl (97 kB)
Requirement already satisfied: grpcio>=1.29.0 in /usr/local/lib/python3.6/site-packages (from grpcio-tools==1.29.0->-r requirements-dev.txt (line 2)) (1.31.0)
Requirement already satisfied: protobuf>=3.5.0.post1 in /usr/local/lib/python3.6/site-packages (from grpcio-tools==1.29.0->-r requirements-dev.txt (line 2)) (3.13.0)
Collecting openapi-spec-validator==0.2.8
  Downloading openapi_spec_validator-0.2.8-py3-none-any.whl (25 kB)
Collecting isort==4.3.21
  Downloading isort-4.3.21-py2.py3-none-any.whl (42 kB)
Collecting argcomplete==1.11.1
  Downloading argcomplete-1.11.1-py2.py3-none-any.whl (36 kB)
Collecting inflect==4.1.0
  Downloading inflect-4.1.0-py3-none-any.whl (31 kB)
Collecting prance==0.18.2
  Downloading prance-0.18.2-py2.py3-none-any.whl (34 kB)
Collecting toml==0.10.1
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting pydantic[email]==1.5.1
  Downloading pydantic-1.5.1-cp36-cp36m-manylinux2014_x86_64.whl (7.4 MB)
Collecting genson==1.2.1
  Downloading genson-1.2.1.tar.gz (33 kB)
Collecting PySnooper==0.4.1
  Downloading PySnooper-0.4.1-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: jinja2==2.11.2 in /usr/local/lib/python3.6/site-packages (from datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (2.11.2)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (8.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (20.4)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (1.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (0.2.5)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (1.9.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (20.2.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/site-packages (from pytest==5.4.3->-r requirements-dev.txt (line 6)) (0.13.1)
Collecting virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0
  Downloading virtualenv-20.0.31-py2.py3-none-any.whl (4.9 MB)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.6/site-packages (from tox==3.18.0->-r requirements-dev.txt (line 8)) (1.15.0)
Collecting filelock>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting typed-ast<1.5.0,>=1.4.0
  Downloading typed_ast-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (737 kB)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.6/site-packages (from mypy==0.782->-r requirements-dev.txt (line 16)) (3.7.4.3)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting click>=6.5
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting regex
  Downloading regex-2020.7.14-cp36-cp36m-manylinux2010_x86_64.whl (660 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf>=3.5.0.post1->grpcio-tools==1.29.0->-r requirements-dev.txt (line 2)) (50.3.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.6/site-packages (from openapi-spec-validator==0.2.8->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (3.2.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.6/site-packages (from openapi-spec-validator==0.2.8->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (5.3.1)
Requirement already satisfied: chardet~=3.0 in /usr/local/lib/python3.6/site-packages (from prance==0.18.2->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (3.0.4)
Collecting semver~=2.9
  Downloading semver-2.10.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: requests~=2.22 in /usr/local/lib/python3.6/site-packages (from prance==0.18.2->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (2.24.0)
Collecting dataclasses>=0.6; python_version < "3.7"
  Downloading dataclasses-0.7-py3-none-any.whl (18 kB)
Collecting email-validator>=1.0.3; extra == "email"
  Downloading email_validator-1.1.1-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from jinja2==2.11.2->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->pytest==5.4.3->-r requirements-dev.txt (line 6)) (2.4.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest==5.4.3->-r requirements-dev.txt (line 6)) (3.1.0)
Collecting importlib-resources>=1.0; python_version < "3.7"
  Downloading importlib_resources-3.0.0-py2.py3-none-any.whl (23 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.6/site-packages (from jsonschema->openapi-spec-validator==0.2.8->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (0.16.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests~=2.22->prance==0.18.2->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests~=2.22->prance==0.18.2->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests~=2.22->prance==0.18.2->datamodel-code-generator==0.5.1->-r requirements-dev.txt (line 3)) (2020.6.20)
Collecting dnspython>=1.15.0
  Downloading dnspython-2.0.0-py3-none-any.whl (208 kB)
Building wheels for collected packages: flake8-black, genson
  Building wheel for flake8-black (setup.py): started
  Building wheel for flake8-black (setup.py): finished with status 'done'
  Created wheel for flake8-black: filename=flake8_black-0.2.0-py2.py3-none-any.whl size=8436 sha256=ff8822e91ddfdb44c37c5c07ec82db3fe00c07d8b59d946e63209c3745af9c3b
  Stored in directory: /builder/home/.cache/pip/wheels/28/82/99/c48b63c1de77baee90f68c9f527a3f81abd214bb890712f084
  Building wheel for genson (setup.py): started
  Building wheel for genson (setup.py): finished with status 'done'
  Created wheel for genson: filename=genson-1.2.1-py2.py3-none-any.whl size=20673 sha256=b2e1a3bba1bd434f24df757f80837d29c1dde6d75b4a6a4b7536836af4871038
  Stored in directory: /builder/home/.cache/pip/wheels/5a/72/99/f5d98a1c6f174ad16f404bf3127a948a1792d0b6bc7ea73185
Successfully built flake8-black genson
Installing collected packages: grpcio-tools, openapi-spec-validator, isort, argcomplete, inflect, semver, prance, toml, dataclasses, dnspython, email-validator, pydantic, appdirs, click, pathspec, regex, typed-ast, black, genson, PySnooper, datamodel-code-generator, pytest, pytest-asyncio, importlib-resources, distlib, filelock, virtualenv, tox, numpy, pycodestyle, pyflakes, mccabe, flake8, flake8-black, mypy-extensions, mypy, mypy-protobuf
  Attempting uninstall: grpcio-tools
    Found existing installation: grpcio-tools 1.31.0
    Uninstalling grpcio-tools-1.31.0:
      Successfully uninstalled grpcio-tools-1.31.0
  Attempting uninstall: pytest
    Found existing installation: pytest 5.3.1
    Uninstalling pytest-5.3.1:
      Successfully uninstalled pytest-5.3.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.1
    Uninstalling numpy-1.19.1:
      Successfully uninstalled numpy-1.19.1
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

alibi 0.5.2 requires tensorflow>=2.0, but you'll have tensorflow 1.15.2 which is incompatible.
Successfully installed PySnooper-0.4.1 appdirs-1.4.4 argcomplete-1.11.1 black-19.10b0 click-7.1.2 dataclasses-0.7 datamodel-code-generator-0.5.1 distlib-0.3.1 dnspython-2.0.0 email-validator-1.1.1 filelock-3.0.12 flake8-3.8.3 flake8-black-0.2.0 genson-1.2.1 grpcio-tools-1.29.0 importlib-resources-3.0.0 inflect-4.1.0 isort-4.3.21 mccabe-0.6.1 mypy-0.782 mypy-extensions-0.4.3 mypy-protobuf-1.23 numpy-1.18.5 openapi-spec-validator-0.2.8 pathspec-0.8.0 prance-0.18.2 pycodestyle-2.6.0 pydantic-1.5.1 pyflakes-2.2.0 pytest-5.4.3 pytest-asyncio-0.14.0 regex-2020.7.14 semver-2.10.2 toml-0.10.1 tox-3.18.0 typed-ast-1.4.1 virtualenv-20.0.31
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
pip install --editable .[all]
Obtaining file:///workspace/source
Requirement already satisfied: grpcio==1.31.0 in /usr/local/lib/python3.6/site-packages (from mlserver==0.1.0) (1.31.0)
Collecting protobuf==3.12.2
  Downloading protobuf-3.12.2-cp36-cp36m-manylinux1_x86_64.whl (1.3 MB)
Collecting fastapi==0.60.1
  Downloading fastapi-0.60.1-py3-none-any.whl (49 kB)
Collecting uvicorn==0.11.6
  Downloading uvicorn-0.11.6-py3-none-any.whl (43 kB)
Collecting orjson==3.3.0
  Downloading orjson-3.3.0-cp36-cp36m-manylinux1_x86_64.whl (207 kB)
Requirement already satisfied: click==7.1.2 in /usr/local/lib/python3.6/site-packages (from mlserver==0.1.0) (7.1.2)
Requirement already satisfied: joblib==0.16.0 in /usr/local/lib/python3.6/site-packages (from mlserver==0.1.0) (0.16.0)
Requirement already satisfied: numpy==1.18.5 in /usr/local/lib/python3.6/site-packages (from mlserver==0.1.0) (1.18.5)
Collecting scikit-learn==0.23.1
  Downloading scikit_learn-0.23.1-cp36-cp36m-manylinux1_x86_64.whl (6.8 MB)
Collecting xgboost==1.1.1
  Downloading xgboost-1.1.1-py3-none-manylinux2010_x86_64.whl (127.6 MB)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from grpcio==1.31.0->mlserver==0.1.0) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf==3.12.2->mlserver==0.1.0) (50.3.0)
Collecting starlette==0.13.6
  Downloading starlette-0.13.6-py3-none-any.whl (59 kB)
Requirement already satisfied: pydantic<2.0.0,>=0.32.2 in /usr/local/lib/python3.6/site-packages (from fastapi==0.60.1->mlserver==0.1.0) (1.5.1)
Collecting h11<0.10,>=0.8
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
Collecting httptools==0.1.*; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy"
  Downloading httptools-0.1.1-cp36-cp36m-manylinux1_x86_64.whl (216 kB)
Collecting websockets==8.*
  Downloading websockets-8.1-cp36-cp36m-manylinux2010_x86_64.whl (78 kB)
Collecting uvloop>=0.14.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy"
  Downloading uvloop-0.14.0-cp36-cp36m-manylinux2010_x86_64.whl (3.9 MB)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.6/site-packages (from scikit-learn==0.23.1->mlserver==0.1.0) (1.5.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.6/site-packages (from scikit-learn==0.23.1->mlserver==0.1.0) (2.1.0)
Requirement already satisfied: dataclasses>=0.6; python_version < "3.7" in /usr/local/lib/python3.6/site-packages (from pydantic<2.0.0,>=0.32.2->fastapi==0.60.1->mlserver==0.1.0) (0.7)
Installing collected packages: protobuf, starlette, fastapi, h11, httptools, websockets, uvloop, uvicorn, orjson, scikit-learn, xgboost, mlserver
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.13.0
    Uninstalling protobuf-3.13.0:
      Successfully uninstalled protobuf-3.13.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
  Running setup.py develop for mlserver
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

alibi 0.5.2 requires tensorflow>=2.0, but you'll have tensorflow 1.15.2 which is incompatible.
Successfully installed fastapi-0.60.1 h11-0.9.0 httptools-0.1.1 mlserver orjson-3.3.0 protobuf-3.12.2 scikit-learn-0.23.1 starlette-0.13.6 uvicorn-0.11.6 uvloop-0.14.0 websockets-8.1 xgboost-1.1.1
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
tox
GLOB sdist-make: /workspace/source/setup.py
py37 create: /workspace/source/.tox/py37
ERROR: invocation failed (exit code 1), logfile: /workspace/source/.tox/py37/log/py37-0.log
================================== log start ===================================
RuntimeError: failed to query /usr/bin/python3.7 with code 1 err: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils import dist\nImportError: cannot import name \'dist\' from \'distutils\' (/usr/lib/python3.7/distutils/__init__.py)\n'

=================================== log end ====================================
ERROR: InvocationError for command /usr/local/bin/python -m virtualenv --no-download --python /usr/bin/python3.7 py37 (exited with code 1)
sklearn create: /workspace/source/.tox/sklearn
sklearn installdeps: -r/workspace/source/requirements-dev.txt
sklearn inst: /workspace/source/.tox/.tmp/package/1/mlserver-0.1.0.zip
sklearn installed: appdirs==1.4.4,argcomplete==1.11.1,attrs==20.2.0,black==19.10b0,certifi==2020.6.20,chardet==3.0.4,click==7.1.2,dataclasses==0.7,datamodel-code-generator==0.5.1,distlib==0.3.1,dnspython==2.0.0,email-validator==1.1.1,fastapi==0.60.1,filelock==3.0.12,flake8==3.8.3,flake8-black==0.2.0,genson==1.2.1,grpcio==1.31.0,grpcio-tools==1.29.0,h11==0.9.0,httptools==0.1.1,idna==2.10,importlib-metadata==1.7.0,importlib-resources==3.0.0,inflect==4.1.0,isort==4.3.21,Jinja2==2.11.2,joblib==0.16.0,jsonschema==3.2.0,MarkupSafe==1.1.1,mccabe==0.6.1,mlserver @ file:///workspace/source/.tox/.tmp/package/1/mlserver-0.1.0.zip,more-itertools==8.5.0,mypy==0.782,mypy-extensions==0.4.3,mypy-protobuf==1.23,numpy==1.18.5,openapi-spec-validator==0.2.8,orjson==3.3.0,packaging==20.4,pathspec==0.8.0,pluggy==0.13.1,prance==0.18.2,protobuf==3.12.2,py==1.9.0,pycodestyle==2.6.0,pydantic==1.5.1,pyflakes==2.2.0,pyparsing==2.4.7,pyrsistent==0.17.3,PySnooper==0.4.1,pytest==5.4.3,pytest-asyncio==0.14.0,PyYAML==5.3.1,regex==2020.7.14,requests==2.24.0,scikit-learn==0.23.1,scipy==1.5.2,semver==2.10.2,six==1.15.0,starlette==0.13.6,threadpoolctl==2.1.0,toml==0.10.1,tox==3.18.0,typed-ast==1.4.1,typing-extensions==3.7.4.3,urllib3==1.25.10,uvicorn==0.11.6,uvloop==0.14.0,virtualenv==20.0.31,wcwidth==0.2.5,websockets==8.1,zipp==3.1.0
sklearn run-test-pre: PYTHONHASHSEED='1382587404'
sklearn run-test: commands[0] | pytest
ImportError while loading conftest '/workspace/source/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from mlserver.handlers import DataPlane
mlserver/__init__.py:2: in <module>
    from .server import MLServer
mlserver/server.py:6: in <module>
    from .model import MLModel
mlserver/model.py:1: in <module>
    from .types import InferenceRequest, InferenceResponse, MetadataModelResponse
E     File "/workspace/source/mlserver/types.py", line 5
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
ERROR: InvocationError for command /workspace/source/.tox/sklearn/bin/pytest (exited with code 4)
xgboost create: /workspace/source/.tox/xgboost
xgboost installdeps: -r/workspace/source/requirements-dev.txt
xgboost inst: /workspace/source/.tox/.tmp/package/1/mlserver-0.1.0.zip
xgboost installed: appdirs==1.4.4,argcomplete==1.11.1,attrs==20.2.0,black==19.10b0,certifi==2020.6.20,chardet==3.0.4,click==7.1.2,dataclasses==0.7,datamodel-code-generator==0.5.1,distlib==0.3.1,dnspython==2.0.0,email-validator==1.1.1,fastapi==0.60.1,filelock==3.0.12,flake8==3.8.3,flake8-black==0.2.0,genson==1.2.1,grpcio==1.31.0,grpcio-tools==1.29.0,h11==0.9.0,httptools==0.1.1,idna==2.10,importlib-metadata==1.7.0,importlib-resources==3.0.0,inflect==4.1.0,isort==4.3.21,Jinja2==2.11.2,jsonschema==3.2.0,MarkupSafe==1.1.1,mccabe==0.6.1,mlserver @ file:///workspace/source/.tox/.tmp/package/1/mlserver-0.1.0.zip,more-itertools==8.5.0,mypy==0.782,mypy-extensions==0.4.3,mypy-protobuf==1.23,numpy==1.18.5,openapi-spec-validator==0.2.8,orjson==3.3.0,packaging==20.4,pathspec==0.8.0,pluggy==0.13.1,prance==0.18.2,protobuf==3.12.2,py==1.9.0,pycodestyle==2.6.0,pydantic==1.5.1,pyflakes==2.2.0,pyparsing==2.4.7,pyrsistent==0.17.3,PySnooper==0.4.1,pytest==5.4.3,pytest-asyncio==0.14.0,PyYAML==5.3.1,regex==2020.7.14,requests==2.24.0,scipy==1.5.2,semver==2.10.2,six==1.15.0,starlette==0.13.6,toml==0.10.1,tox==3.18.0,typed-ast==1.4.1,typing-extensions==3.7.4.3,urllib3==1.25.10,uvicorn==0.11.6,uvloop==0.14.0,virtualenv==20.0.31,wcwidth==0.2.5,websockets==8.1,xgboost==1.1.1,zipp==3.1.0
xgboost run-test-pre: PYTHONHASHSEED='1382587404'
xgboost run-test: commands[0] | pytest
ImportError while loading conftest '/workspace/source/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from mlserver.handlers import DataPlane
mlserver/__init__.py:2: in <module>
    from .server import MLServer
mlserver/server.py:6: in <module>
    from .model import MLModel
mlserver/model.py:1: in <module>
    from .types import InferenceRequest, InferenceResponse, MetadataModelResponse
E     File "/workspace/source/mlserver/types.py", line 5
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
ERROR: InvocationError for command /workspace/source/.tox/xgboost/bin/pytest (exited with code 4)
all create: /workspace/source/.tox/all
all installdeps: -r/workspace/source/requirements-dev.txt
all inst: /workspace/source/.tox/.tmp/package/1/mlserver-0.1.0.zip
all installed: appdirs==1.4.4,argcomplete==1.11.1,attrs==20.2.0,black==19.10b0,certifi==2020.6.20,chardet==3.0.4,click==7.1.2,dataclasses==0.7,datamodel-code-generator==0.5.1,distlib==0.3.1,dnspython==2.0.0,email-validator==1.1.1,fastapi==0.60.1,filelock==3.0.12,flake8==3.8.3,flake8-black==0.2.0,genson==1.2.1,grpcio==1.31.0,grpcio-tools==1.29.0,h11==0.9.0,httptools==0.1.1,idna==2.10,importlib-metadata==1.7.0,importlib-resources==3.0.0,inflect==4.1.0,isort==4.3.21,Jinja2==2.11.2,joblib==0.16.0,jsonschema==3.2.0,MarkupSafe==1.1.1,mccabe==0.6.1,mlserver @ file:///workspace/source/.tox/.tmp/package/1/mlserver-0.1.0.zip,more-itertools==8.5.0,mypy==0.782,mypy-extensions==0.4.3,mypy-protobuf==1.23,numpy==1.18.5,openapi-spec-validator==0.2.8,orjson==3.3.0,packaging==20.4,pathspec==0.8.0,pluggy==0.13.1,prance==0.18.2,protobuf==3.12.2,py==1.9.0,pycodestyle==2.6.0,pydantic==1.5.1,pyflakes==2.2.0,pyparsing==2.4.7,pyrsistent==0.17.3,PySnooper==0.4.1,pytest==5.4.3,pytest-asyncio==0.14.0,PyYAML==5.3.1,regex==2020.7.14,requests==2.24.0,scikit-learn==0.23.1,scipy==1.5.2,semver==2.10.2,six==1.15.0,starlette==0.13.6,threadpoolctl==2.1.0,toml==0.10.1,tox==3.18.0,typed-ast==1.4.1,typing-extensions==3.7.4.3,urllib3==1.25.10,uvicorn==0.11.6,uvloop==0.14.0,virtualenv==20.0.31,wcwidth==0.2.5,websockets==8.1,xgboost==1.1.1,zipp==3.1.0
all run-test-pre: PYTHONHASHSEED='1382587404'
all run-test: commands[0] | pytest
ImportError while loading conftest '/workspace/source/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from mlserver.handlers import DataPlane
mlserver/__init__.py:2: in <module>
    from .server import MLServer
mlserver/server.py:6: in <module>
    from .model import MLModel
mlserver/model.py:1: in <module>
    from .types import InferenceRequest, InferenceResponse, MetadataModelResponse
E     File "/workspace/source/mlserver/types.py", line 5
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
ERROR: InvocationError for command /workspace/source/.tox/all/bin/pytest (exited with code 4)
___________________________________ summary ____________________________________
ERROR:   py37: InvocationError for command /usr/local/bin/python -m virtualenv --no-download --python /usr/bin/python3.7 py37 (exited with code 1)
ERROR:   sklearn: commands failed
ERROR:   xgboost: commands failed
ERROR:   all: commands failed
make: *** [Makefile:22: test] Error 1
[31m
Pipeline failed on stage 'test-python' : container 'step-test-python'. The execution of the pipeline has stopped.[0m
